# Generated by Django 4.2 on 2023-04-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('coor', models.CharField(max_length=255)),
                ('har', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'shelter',
            },
        ),
    ]
