# Generated by Django 4.2 on 2023-07-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_shelter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
