# Generated by Django 4.2 on 2023-07-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_author_remove_post_tags_delete_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities_maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name_client', models.CharField(max_length=250)),
                ('city_name_product', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.DeleteModel(
            name='Shelter',
        ),
    ]
